// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKoRGg_g-drjQbOwyeA2kN36MA7YEs_s8',
    appId: '1:356823887457:web:40d14c491419b58b404420',
    messagingSenderId: '356823887457',
    projectId: 'fccapp-4220d',
    authDomain: 'fccapp-4220d.firebaseapp.com',
    storageBucket: 'fccapp-4220d.appspot.com',
    measurementId: 'G-RC291FJY6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJdqxRuH81e8S5pZCgK4TWnN8aOrFUUx4',
    appId: '1:356823887457:android:c1658bdfdede5b6f404420',
    messagingSenderId: '356823887457',
    projectId: 'fccapp-4220d',
    storageBucket: 'fccapp-4220d.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN-_pOhRjNSpDmvRRdbJnfv7uVGHsQuxk',
    appId: '1:356823887457:ios:3478495876968386404420',
    messagingSenderId: '356823887457',
    projectId: 'fccapp-4220d',
    storageBucket: 'fccapp-4220d.appspot.com',
    iosBundleId: 'com.example.fcccontrolcenter.RunnerTests',
  );
}
